
[auth]
cookie_name = "ag-genetics-auth"
cookie_ttl_days = 30

[users.jason_bragg]
email = "jsnbrgg@gmail.com"
password_hash = "pbkdf2_sha256$260000$1tFzzFaduWct1PWvoY6QXg==$VNedzojLJ1M4jOVJ+wZUiIQXOKnMgrCgN9/U5kUu+vE="
role = "admin"

[users.ronnie_midkiff]
email = "rsmidkiff@ymail.com"
password_hash = "pbkdf2_sha256$260000$2MYQdr7WG96RdYC+RO44IA==$svAWr26CloeIQcIQB7Bs4g7K0hrOkWdW0pOLLzSvV7o="
role = "viewer"

[users.chris_rodebaugh]
email = "crodebaugh@ymail.com"
password_hash = "pbkdf2_sha256$260000$j+S/X6o8xwAUqcaOpTxtug==$Z+HEl7AuODRH3pHErW8tdzufyNla5/Fpyh+JJqKJoUQ="
role = "viewer"
