[auth]
cookie_name = "ag-genetics-auth"
cookie_ttl_days = 30

[users.jason]
email = "jsnbrgg@gmail.com"
password_hash = "pbkdf2_sha256$260000$U+/DlkqB0v8m9SZDJF5ioA==$rQWT+PuhZvAeBD6sq+kc+T3GZHyhaVFyq27b/RJ8t6k="
role = "admin"

[users.ronnie]
email = "rsmidkiff@ymail.com"
password_hash = "pbkdf2_sha256$260000$DQgr9n1Tu4ei2dfSH8wpWA==$Ea2Wjf1sqzLTk7OW8RjEys5mZbp38ny/pgcNfTP/SPY="
role = "viewer"

[users.chris]
email = "crodebaugh@ymail.com"
password_hash = "pbkdf2_sha256$260000$xU6oBDvsRxcxffLaEo8uUg==$+R6Fu4GD16yiSonJu07u8VOdzjOcmB9jPxpQBrsq1lM="
role = "viewer"
